<RootWidget>

<LoginScreen>

    GridLayout:
        pos_hint:{'center_x':.5, 'center_y':.35}
        row_default_height: 5
        size_hint: .9, .2
        cols:1
        spacing: 5
        Button:
            id:start_discovery
            text:'Turn on Discovery'
            on_press: root.turnOnDiscovery()
        Button:
            id: find_devices
            text:'Find Devices'
            on_press: root.findDevices()
            

